version: '3.7'

services:
  local-mysql:
    image: mysql:8.0.22
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3307:3306"
    restart: unless-stopped
    volumes:
      - mysqldata:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
volumes:
  mysqldata: